### ISSUE TITLE
Post creation bug: User and Comment ids.

### ISSUE THREAD

**Issue by Gilbertstrang** [Gilbertstrang/SWE573-Fall24#19]
Post creation requires User entity and comment ids. Needing a user entity is overkill, change it to user's id. Also, comment id is dumb because in the creation of a post, there would be no comments!!!

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the Post model to use userId instead of User entity. Updated PostDto to remove comments field. Changed PostService to work with userId instead of User entity and removed comment-related logic during post creation.

You can review changes in this commit: https://github.com/jjyutm4532/Gilbertstrang-SWE573-Fall24-19/commit/9bb729fd97906c03e5c39dda1bb084cead98c01b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Gilbertstrang** [comment]
Comment id problem: It now opens an empty array for future comments. So it does not need unexisting comment ids. They are gone.

User id problem: Changed postDTO a bit, now it feeds username rather than whole User entity. Then from username we get userId etc. Not really happy with this solution, felt it was a bit bandaid solution but oh well.
